In [6]:
# http://scikit-learn.org/stable/auto_examples/classification/plot_digits_classification.html
# support vector machine from scikit-learn

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import svm

In [8]:
# Import data from training sets
with open('optdigits-orig_train.txt') as f:
    train_data = []
    train_label = []
    temp = []
    for i, line in enumerate(f):
        if i % 33 == 32:
            temp = np.asarray(temp).reshape((1024,))
            train_data.append(temp)
            train_label.append(int(line[1]))
            temp = []
        else:
            temp.append([int(x) for x in list(str(line))[:-1]])
train_label = np.asarray(train_label)
train_data = np.asarray(train_data)

In [9]:
# Import data from test sets
with open('optdigits-orig_test.txt') as f:
    test_data = []
    test_label = []
    temp = []
    for i, line in enumerate(f):
        if i % 33 == 32:
            temp = np.asarray(temp).reshape((1024,))
            test_data.append(temp)
            test_label.append(int(line[1]))
            temp = []
        else:
            temp.append([int(x) for x in list(str(line))[:-1]])
test_label = np.asarray(test_label)
test_data = np.asarray(test_data)

In [22]:
### default svm by scikit-learn
clf = svm.SVC()
clf.fit(train_data, train_label)
svm_label = clf.predict(test_data)
confusion = np.zeros((10,10))
for i in range(test_label.shape[0]):
    confusion[test_label[i]][svm_label[i]] += 1
print(confusion)
print("Accuracy is {}".format(1-(np.count_nonzero(test_label-svm_label)/test_label.shape[0])))

[[36.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 44.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0. 36.  0.  0.  0.  0.  0.  4.  1.]
 [ 0.  0.  0. 31.  0.  0.  0.  0.  0.  2.]
 [ 0.  0.  0.  0. 57.  0.  0.  0.  2.  0.]
 [ 0.  0.  0.  0.  0. 58.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0. 42.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0. 46.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 40.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  1.  0. 40.]]
Accuracy is 0.9684684684684685


In [21]:
### svm with gamma=0.01
clf = svm.SVC(gamma=0.01)
clf.fit(train_data, train_label)
svm_label = clf.predict(test_data)
confusion = np.zeros((10,10))
for i in range(test_label.shape[0]):
    confusion[test_label[i]][svm_label[i]] += 1
print(confusion)
print("Accuracy is {}".format(1-(np.count_nonzero(test_label-svm_label)/test_label.shape[0])))

[[36.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 44.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0. 40.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0. 33.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 59.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 58.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0. 42.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 47.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 40.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 42.]]
Accuracy is 0.9932432432432432
