In [114]:
import numpy as np
a = np.zeros((7,7))
#a[3:7,6] = 1
a[2,0] = 1
a[0,1] = 1
a[3,0] = 1
# a[6,3] = 1
a[0,4] = 2
a[1,3] = 2
a[2,2] = 2
a[3,1] = 2
# a[1:5,1] = 2
print(a)

[[ 0.  1.  0.  0.  2.  0.  0.]
 [ 0.  0.  0.  2.  0.  0.  0.]
 [ 1.  0.  2.  0.  0.  0.  0.]
 [ 1.  2.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [12]:
np.count_nonzero(a == 1)

4

In [115]:
# functions
# gomoku() input the matrix, output the matrix after one move
# rule1() 
# rule2()
# rule3()
# rule4()

def rule1(arr,n): #input (matrix, whose turn)
    # check for horizontal 4 consecutive stones
    for i in range(7):
        for j in range(4):
            if (arr[i][j] == n and arr[i][j+1] == n and arr[i][j+2] == n and arr[i][j+3] == n):
                if (j >= 1 and arr[i][j-1] == 0):
                    return (i, j-1)
                if (j <= 2 and arr[i][j+4] == 0):
                    return (i, j+4)
    # check for vertical 4 consecutive stones
    for i in range(4):
        for j in range(7):
            if (arr[i][j] == n and arr[i+1][j] == n and arr[i+2][j] == n and arr[i+3][j] == n):
                if (i <= 2 and arr[i+4][j] == 0):
                    return (i+4, j)
                if (i >= 1 and arr[i-1][j] == 0):
                    return (i-1, j)
    # check for y = -x diagonal 4 consecutive stones
    for (i,j) in [(2,0), (3,1), (1,0), (2,1), (3,2), (0,0), (1,1), (2,2), (3,3), (0,1), (1,2), (2,3), (0,2), (1,3)]:
        if (arr[i][j] == n and arr[i+1][j+1] == n and arr[i+2][j+2] == n and arr[i+3][j+3] == n):
                if (i >= 1 and j >= 1 and arr[i-1][j-1] == 0):
                    return (i-1, j-1)
                if (i <= 2 and j <= 2 and arr[i+4][j+4] == 0):
                    return (i+4, j+4)
    # check for y = x diagonal 4 consecutive stones
    for (i,j) in [(2,6), (3,5), (1,6), (2,5), (3,4), (0,6), (1,5), (2,4), (3,3), (0,5), (1,4), (2,3), (0,4), (1,3)]:
        if (arr[i][j] == n and arr[i+1][j-1] == n and arr[i+2][j-2] == n and arr[i+3][j-3] == n):
                if (i >= 1 and j <= 5 and arr[i-1][j+1] == 0):
                    return (i-1, j+1)
                if (i <= 2 and j >= 4 and arr[i+4][j-4] == 0):
                    return (i+4, j-4)
    return None

print (rule1(a,1))

None


In [116]:
def rule2(arr,n):
    o = 3 - n # opponent's notation since 1+2=3
    # check for horizontal unbroken chain formed by 4 stones + empty intersection on either head of the chain
#     for i in range(7):
#         for j in range(2):
#             if (arr[i][j+1] == o and arr[i][j+2] == o and arr[i][j+3] == o and arr[i][j+4] == o):
#                 if (arr[i][j] == 0 and arr[i][j+5] == n):
#                     return (i, j)
#                 if (arr[i][j] == n and arr[i][j+5] == 0):
#                     return (i, j+5)
#     for i in range(7):
#         if (arr[i][0] == o and arr[i][1] == o and arr[i][2] == o and arr[i][3] == o and arr[i][4] == 0):
#             return (i,4)
#         if (arr[i][6] == o and arr[i][5] == o and arr[i][4] == o and arr[i][3] == o and arr[i][2] == 0):
#             return (i,2)
    for i in range(7):
        for j in range(4):
            if (arr[i][j] == o and arr[i][j+1] == o and arr[i][j+2] == o and arr[i][j+3] == o):
                if (j >= 1 and arr[i][j-1] == 0):
                    return (i, j-1)
                if (j <= 2 and arr[i][j+4] == 0):
                    return (i, j+4)
    # check for vertical unbroken chain formed by 4 stones + empty intersection on either head of the chain
#     for i in range(2):
#         for j in range(7):
#             if (arr[i+1][j] == o and arr[i+2][j] == o and arr[i+3][j] == o and arr[i+4][j] == o):
#                 if (arr[i][j] == 0 and arr[i+5][j] == n):
#                     return (i, j)
#                 if (arr[i][j] == n and arr[i+5][j] == 0):
#                     return (i+5, j)
#     for j in range(7):
#         if (arr[0][j] == o and arr[1][j] == o and arr[2][j] == o and arr[3][j] == o and arr[4][j] == 0):
#             return (4,j)
#         if (arr[6][j] == o and arr[5][j] == o and arr[4][j] == o and arr[3][j] == o and arr[2][j] == 0):
#             return (2,j)
    for i in range(4):
        for j in range(7):
            if (arr[i][j] == o and arr[i+1][j] == o and arr[i+2][j] == o and arr[i+3][j] == o):
                if (i <= 2 and arr[i+4][j] == 0):
                    return (i+4, j)
                if (i >= 1 and arr[i-1][j] == 0):
                    return (i-1, j)
    # check for diagonal y = -x unbroken chain formed by 4 stones + empty intersection on either head of the chain
    for (i,j) in [(2,0), (3,1), (1,0), (2,1), (3,2), (0,0), (1,1), (2,2), (3,3), (0,1), (1,2), (2,3), (0,2), (1,3)]:
        if (arr[i][j] == o and arr[i+1][j+1] == o and arr[i+2][j+2] == o and arr[i+3][j+3] == o):
                if (i >= 1 and j >= 1 and arr[i-1][j-1] == 0):
                    return (i-1, j-1)
                if (i <= 2 and j <= 2 and arr[i+4][j+4] == 0):
                    return (i+4, j+4)
    # check for diagonal y = x unbroken chain formed by 4 stones + empty intersection on either head of the chain
    for (i,j) in [(2,6), (3,5), (1,6), (2,5), (3,4), (0,6), (1,5), (2,4), (3,3), (0,5), (1,4), (2,3), (0,4), (1,3)]:
        if (arr[i][j] == o and arr[i+1][j-1] == o and arr[i+2][j-2] == o and arr[i+3][j-3] == o):
                if (i >= 1 and j <= 5 and arr[i-1][j+1] == 0):
                    return (i-1, j+1)
                if (i <= 2 and j >= 4 and arr[i+4][j-4] == 0):
                    return (i+4, j-4)
    return None

print (rule2(a,1))

(4, 0)


In [ ]:
def rule3(arr,n):
    