In [102]:
def rule1(arr,n): #input (matrix, whose turn)
    # check for horizontal 4 consecutive stones
    for i in range(7):
        for j in range(4):
            if (arr[i][j] == n and arr[i][j+1] == n and arr[i][j+2] == n and arr[i][j+3] == n):
                if (j >= 1 and arr[i][j-1] == 0):
                    return (i, j-1)
                if (j <= 2 and arr[i][j+4] == 0):
                    return (i, j+4)
    # check for vertical 4 consecutive stones
    for i in range(4):
        for j in range(7):
            if (arr[i][j] == n and arr[i+1][j] == n and arr[i+2][j] == n and arr[i+3][j] == n):
                if (i <= 2 and arr[i+4][j] == 0):
                    return (i+4, j)
                if (i >= 1 and arr[i-1][j] == 0):
                    return (i-1, j)
    # check for y = -x diagonal 4 consecutive stones
    for (i,j) in [(2,0), (3,1), (1,0), (2,1), (3,2), (0,0), (1,1), (2,2), (3,3), (0,1), (1,2), (2,3), (0,2), (1,3)]:
        if (arr[i][j] == n and arr[i+1][j+1] == n and arr[i+2][j+2] == n and arr[i+3][j+3] == n):
                if (i >= 1 and j >= 1 and arr[i-1][j-1] == 0):
                    return (i-1, j-1)
                if (i <= 2 and j <= 2 and arr[i+4][j+4] == 0):
                    return (i+4, j+4)
    # check for y = x diagonal 4 consecutive stones
    for (i,j) in [(2,6), (3,5), (1,6), (2,5), (3,4), (0,6), (1,5), (2,4), (3,3), (0,5), (1,4), (2,3), (0,4), (1,3)]:
        if (arr[i][j] == n and arr[i+1][j-1] == n and arr[i+2][j-2] == n and arr[i+3][j-3] == n):
                if (i >= 1 and j <= 5 and arr[i-1][j+1] == 0):
                    return (i-1, j+1)
                if (i <= 2 and j >= 4 and arr[i+4][j-4] == 0):
                    return (i+4, j-4)
    return None

print (rule1(a,1))

None


In [103]:
def rule2(arr,n):
    o = 3 - n # opponent's notation since 1+2=3
    # check for horizontal unbroken chain formed by 4 stones + empty intersection on either head of the chain
    for i in range(7):
        for j in range(4):
            if (arr[i][j] == o and arr[i][j+1] == o and arr[i][j+2] == o and arr[i][j+3] == o):
                if (j >= 1 and arr[i][j-1] == 0):
                    return (i, j-1)
                if (j <= 2 and arr[i][j+4] == 0):
                    return (i, j+4)
    # check for vertical unbroken chain formed by 4 stones + empty intersection on either head of the chain
    for i in range(4):
        for j in range(7):
            if (arr[i][j] == o and arr[i+1][j] == o and arr[i+2][j] == o and arr[i+3][j] == o):
                if (i <= 2 and arr[i+4][j] == 0):
                    return (i+4, j)
                if (i >= 1 and arr[i-1][j] == 0):
                    return (i-1, j)
    # check for diagonal y = -x unbroken chain formed by 4 stones + empty intersection on either head of the chain
    for (i,j) in [(2,0), (3,1), (1,0), (2,1), (3,2), (0,0), (1,1), (2,2), (3,3), (0,1), (1,2), (2,3), (0,2), (1,3)]:
        if (arr[i][j] == o and arr[i+1][j+1] == o and arr[i+2][j+2] == o and arr[i+3][j+3] == o):
                if (i >= 1 and j >= 1 and arr[i-1][j-1] == 0):
                    return (i-1, j-1)
                if (i <= 2 and j <= 2 and arr[i+4][j+4] == 0):
                    return (i+4, j+4)
    # check for diagonal y = x unbroken chain formed by 4 stones + empty intersection on either head of the chain
    for (i,j) in [(2,6), (3,5), (1,6), (2,5), (3,4), (0,6), (1,5), (2,4), (3,3), (0,5), (1,4), (2,3), (0,4), (1,3)]:
        if (arr[i][j] == o and arr[i+1][j-1] == o and arr[i+2][j-2] == o and arr[i+3][j-3] == o):
                if (i >= 1 and j <= 5 and arr[i-1][j+1] == 0):
                    return (i-1, j+1)
                if (i <= 2 and j >= 4 and arr[i+4][j-4] == 0):
                    return (i+4, j-4)
    return None

print (rule2(a,1))

(1, 5)


In [104]:
def rule3(arr,n):
    o = 3 - n
    # horizontal
    for i in range(7):
        for j in range(3):
            if (arr[i][j+1] == o and arr[i][j+2] == o and arr[i][j+3] == o and arr[i][j] == 0 and arr[i][j+4] == 0):
                return (i,j)
    # vertical
    for i in range(3):
        for j in range(7):
            if (arr[i+1][j] == o and arr[i+2][j] == o and arr[i+3][j] == o and arr[i][j] == 0 and arr[i+4][j] == 0):
                return (i+4, j)
    # y = -x
    for i in range(3):
        for j in range(3):
            if (arr[i][j] == 0 and arr[i+1][j+1] == o and arr[i+2][j+2] == o and arr[i+3][j+3] == o and arr[i+4][j+4] == 0):
                return (i, j)
    # y = x
    for i in range(0, 3):
        for j in range(4, 7):
            if (arr[i][j] == 0 and arr[i+1][j-1] == o and arr[i+2][j-2] == o and arr[i+3][j-3] == o and arr[i+4][j-4] == 0):
                return (i+4, j-4)
    return None

print (rule3(a,1))

None


In [117]:
def rule4(arr,n):
    o = 3 - n
    temp = []
    # horizontal
    for i in range(7):
        for j in range(3):
            if (np.count_nonzero(arr[i, j:j+5] == o) == 0):
                temp.append((i, (np.nonzero(a[i, j:j+5] == 0)[0][0] + j), np.count_nonzero(arr[i, j:j+5] == n)))
    # vertical
    for i in range(3):
        for j in range(7):
            if (np.count_nonzero(arr[i:i+5, j] == o) == 0):
                temp.append(((np.nonzero(a[i:i+5, j] == 0)[0][::-1][0] + i, j, np.count_nonzero(arr[i:i+5, j] == n))))
    # y = -x
    for i in range(3):
        for j in range(3):
            if (np.count_nonzero(arr[i:i+5, j:j+5].diagonal() == o) == 0):
                c = np.nonzero(a[i:i+5, j:j+5].diagonal() == 0)[0][0]
                temp.append(((i + c, j + c, np.count_nonzero(arr[i:i+5, j:j+5].diagonal() == n))))
    # y = x
    for i in range(0, 3):
        for j in range(4, 7):
            if (np.count_nonzero(np.flipud(arr[i:i+5, j-4:j+1]).diagonal()[::-1] == o) == 0):
                c = np.nonzero(np.flipud(arr[i:i+5, j-4:j+1]).diagonal()[::-1] == 0)[0][::-1][0]
                temp.append(((i + c, j - c, np.count_nonzero(np.flipud(arr[i:i+5, j-4:j+1]).diagonal()[::-1] == n))))
    
    temp = list(set(temp))
    temp_sorted = sorted(temp, key = lambda x : (-x[2], x[1], -x[0]))
    return (temp_sorted[0][0:2])

print (rule4(a, 2))

(6, 0)


In [106]:
# check if the game has terminated (either five stones in a row or no available spaces)
def terminate(arr):
    if (np.count_nonzero(arr == 0) == 0):
        return True;
    # horizontal
    for i in range(7):
        for j in range(3):
            if (arr[i][j+1] == 1 and arr[i][j+2] == 1 and arr[i][j+3] == 1 and arr[i][j] == 1 and arr[i][j+4] == 1):
                return True
            if (arr[i][j+1] == 2 and arr[i][j+2] == 2 and arr[i][j+3] == 2 and arr[i][j] == 2 and arr[i][j+4] == 2):
                return True
    # vertical
    for i in range(3):
        for j in range(7):
            if (arr[i+1][j] == 1 and arr[i+2][j] == 1 and arr[i+3][j] == 1 and arr[i][j] == 1 and arr[i+4][j] == 1):
                return True
            if (arr[i+1][j] == 2 and arr[i+2][j] == 2 and arr[i+3][j] == 2 and arr[i][j] == 2 and arr[i+4][j] == 2):
                return True
    # y = -x
    for i in range(3):
        for j in range(3):
            if (arr[i][j] == 1 and arr[i+1][j+1] == 1 and arr[i+2][j+2] == 1 and arr[i+3][j+3] == 1 and arr[i+4][j+4] == 1):
                return True
            if (arr[i][j] == 2 and arr[i+1][j+1] == 2 and arr[i+2][j+2] == 2 and arr[i+3][j+3] == 2 and arr[i+4][j+4] == 2):
                return True
    # y = x
    for i in range(0, 3):
        for j in range(4, 7):
            if (arr[i][j] == 1 and arr[i+1][j-1] == 1 and arr[i+2][j-2] == 1 and arr[i+3][j-3] == 1 and arr[i+4][j-4] == 1):
                return True
            if (arr[i][j] == 2 and arr[i+1][j-1] == 2 and arr[i+2][j-2] == 2 and arr[i+3][j-3] == 2 and arr[i+4][j-4] == 2):
                return True
    return False

print (terminate(a))

True


In [120]:
import numpy as np
a = np.zeros((7,7)) # showing board at each step
# a[1,1] = 2
# a[3,2] = 2
# a[0,6] = 1
# a[6,0] = 2

print (a)
abc = np.chararray((7,7), unicode = True) # showing required board labeled "A-Z", "a-z" and "."

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [121]:
n = 2 # so that 1 starts first when entering the while loop
first = 97 # chr(97) = "a"
second = 65 # chr(65) = "A"

while (not terminate(a)):
    print (a)
    n = 3 - n;
    if rule1(a, n):
        b = rule1(a, n)
        a[b[0], b[1]] = n
        if (n == 1):
            abc[b[0], b[1]] = chr(first)
            first += 1
        if (n == 2):
            abc[b[0], b[1]] = chr(second)
            second += 1
        continue
    if rule2(a, n):
        b = rule2(a, n)
        a[b[0], b[1]] = n
        if (n == 1):
            abc[b[0], b[1]] = chr(first)
            first += 1
        if (n == 2):
            abc[b[0], b[1]] = chr(second)
            second += 1
        continue
    if rule3(a, n):
        b = rule3(a, n)
        a[b[0], b[1]] = n
        if (n == 1):
            abc[b[0], b[1]] = chr(first)
            first += 1
        if (n == 2):
            abc[b[0], b[1]] = chr(second)
            second += 1
        continue
    if rule4(a, n):
        b = rule4(a, n)
        a[b[0], b[1]] = n
        if (n == 1):
            abc[b[0], b[1]] = chr(first)
            first += 1
        if (n == 2):
            abc[b[0], b[1]] = chr(second)
            second += 1
        continue

print (a)

for i in range(7):
    for j in range(7):
        if abc[i][j] == '':
            abc[i][j] = '.'

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 2.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 2.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 2

In [122]:
print(abc)

[['.' '.' '.' '.' '.' '.' '.']
 ['f' 'l' '.' '.' 'k' '.' '.']
 ['E' 'K' 'L' 'J' 'H' '.' '.']
 ['C' 'F' 'G' 'h' '.' '.' '.']
 ['B' 'I' 'g' 'j' '.' '.' '.']
 ['A' 'e' '.' 'i' '.' '.' '.']
 ['a' 'b' 'c' 'd' 'D' '.' '.']]
