In [2]:
import numpy as np
a = np.zeros((7,7)) # showing board at each step
# a[1,1] = 2
# a[3,2] = 2
a[1,5] = 2
a[5,1] = 1

print (a)
abc = np.chararray((7,7), unicode = True) # showing required board labeled "A-Z", "a-z" and "."

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  2.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [3]:
def rule1(arr,n): #input (matrix, whose turn)
    # check for horizontal 4 consecutive stones
    for i in range(7):
        for j in range(4):
            if (arr[i][j] == n and arr[i][j+1] == n and arr[i][j+2] == n and arr[i][j+3] == n):
                if (j >= 1 and arr[i][j-1] == 0):
                    return (i, j-1)
                if (j <= 2 and arr[i][j+4] == 0):
                    return (i, j+4)
    # check for vertical 4 consecutive stones
    for i in range(4):
        for j in range(7):
            if (arr[i][j] == n and arr[i+1][j] == n and arr[i+2][j] == n and arr[i+3][j] == n):
                if (i <= 2 and arr[i+4][j] == 0):
                    return (i+4, j)
                if (i >= 1 and arr[i-1][j] == 0):
                    return (i-1, j)
    # check for y = -x diagonal 4 consecutive stones
    for (i,j) in [(2,0), (3,1), (1,0), (2,1), (3,2), (0,0), (1,1), (2,2), (3,3), (0,1), (1,2), (2,3), (0,2), (1,3)]:
        if (arr[i][j] == n and arr[i+1][j+1] == n and arr[i+2][j+2] == n and arr[i+3][j+3] == n):
                if (i >= 1 and j >= 1 and arr[i-1][j-1] == 0):
                    return (i-1, j-1)
                if (i <= 2 and j <= 2 and arr[i+4][j+4] == 0):
                    return (i+4, j+4)
    # check for y = x diagonal 4 consecutive stones
    for (i,j) in [(2,6), (3,5), (1,6), (2,5), (3,4), (0,6), (1,5), (2,4), (3,3), (0,5), (1,4), (2,3), (0,4), (1,3)]:
        if (arr[i][j] == n and arr[i+1][j-1] == n and arr[i+2][j-2] == n and arr[i+3][j-3] == n):
                if (i >= 1 and j <= 5 and arr[i-1][j+1] == 0):
                    return (i-1, j+1)
                if (i <= 2 and j >= 4 and arr[i+4][j-4] == 0):
                    return (i+4, j-4)
    return None

# print (rule1(a,1))

In [4]:
def rule2(arr,n):
    o = 3 - n # opponent's notation since 1+2=3
    # check for horizontal unbroken chain formed by 4 stones + empty intersection on either head of the chain
    for i in range(7):
        for j in range(4):
            if (arr[i][j] == o and arr[i][j+1] == o and arr[i][j+2] == o and arr[i][j+3] == o):
                if (j >= 1 and arr[i][j-1] == 0):
                    return (i, j-1)
                if (j <= 2 and arr[i][j+4] == 0):
                    return (i, j+4)
    # check for vertical unbroken chain formed by 4 stones + empty intersection on either head of the chain
    for i in range(4):
        for j in range(7):
            if (arr[i][j] == o and arr[i+1][j] == o and arr[i+2][j] == o and arr[i+3][j] == o):
                if (i <= 2 and arr[i+4][j] == 0):
                    return (i+4, j)
                if (i >= 1 and arr[i-1][j] == 0):
                    return (i-1, j)
    # check for diagonal y = -x unbroken chain formed by 4 stones + empty intersection on either head of the chain
    for (i,j) in [(2,0), (3,1), (1,0), (2,1), (3,2), (0,0), (1,1), (2,2), (3,3), (0,1), (1,2), (2,3), (0,2), (1,3)]:
        if (arr[i][j] == o and arr[i+1][j+1] == o and arr[i+2][j+2] == o and arr[i+3][j+3] == o):
                if (i >= 1 and j >= 1 and arr[i-1][j-1] == 0):
                    return (i-1, j-1)
                if (i <= 2 and j <= 2 and arr[i+4][j+4] == 0):
                    return (i+4, j+4)
    # check for diagonal y = x unbroken chain formed by 4 stones + empty intersection on either head of the chain
    for (i,j) in [(2,6), (3,5), (1,6), (2,5), (3,4), (0,6), (1,5), (2,4), (3,3), (0,5), (1,4), (2,3), (0,4), (1,3)]:
        if (arr[i][j] == o and arr[i+1][j-1] == o and arr[i+2][j-2] == o and arr[i+3][j-3] == o):
                if (i <= 2 and j >= 4 and arr[i+4][j-4] == 0):
                    return (i+4, j-4)
                if (i >= 1 and j <= 5 and arr[i-1][j+1] == 0):
                    return (i-1, j+1)

    return None

# print (rule2(a,1))

In [5]:
def rule3(arr,n):
    o = 3 - n
    # horizontal
    for i in range(7):
        for j in range(3):
            if (arr[i][j+1] == o and arr[i][j+2] == o and arr[i][j+3] == o and arr[i][j] == 0 and arr[i][j+4] == 0):
                return (i,j)
    # vertical
    for i in range(3):
        for j in range(7):
            if (arr[i+1][j] == o and arr[i+2][j] == o and arr[i+3][j] == o and arr[i][j] == 0 and arr[i+4][j] == 0):
                return (i+4, j)
    # y = -x
    for i in range(3):
        for j in range(3):
            if (arr[i][j] == 0 and arr[i+1][j+1] == o and arr[i+2][j+2] == o and arr[i+3][j+3] == o and arr[i+4][j+4] == 0):
                return (i, j)
    # y = x
    for i in range(0, 3):
        for j in range(4, 7):
            if (arr[i][j] == 0 and arr[i+1][j-1] == o and arr[i+2][j-2] == o and arr[i+3][j-3] == o and arr[i+4][j-4] == 0):
                return (i+4, j-4)
    return None

# print (rule3(a,1))

In [6]:
def rule4(arr,n):
    o = 3 - n
    temp = []
    # horizontal
    for i in range(7):
        for j in range(3):
            if (np.count_nonzero(arr[i, j:j+5] == o) == 0):
                temp.append((i, (np.nonzero(a[i, j:j+5] == 0)[0][0] + j), np.count_nonzero(arr[i, j:j+5] == n)))
    # vertical
    for i in range(3):
        for j in range(7):
            if (np.count_nonzero(arr[i:i+5, j] == o) == 0):
                temp.append(((np.nonzero(a[i:i+5, j] == 0)[0][::-1][0] + i, j, np.count_nonzero(arr[i:i+5, j] == n))))
    # y = -x
    for i in range(3):
        for j in range(3):
            if (np.count_nonzero(arr[i:i+5, j:j+5].diagonal() == o) == 0):
                c = np.nonzero(a[i:i+5, j:j+5].diagonal() == 0)[0][0]
                temp.append(((i + c, j + c, np.count_nonzero(arr[i:i+5, j:j+5].diagonal() == n))))
    # y = x
    for i in range(0, 3):
        for j in range(4, 7):
            if (np.count_nonzero(np.flipud(arr[i:i+5, j-4:j+1]).diagonal()[::-1] == o) == 0):
                c = np.nonzero(np.flipud(arr[i:i+5, j-4:j+1]).diagonal()[::-1] == 0)[0][::-1][0]
                temp.append(((i + c, j - c, np.count_nonzero(np.flipud(arr[i:i+5, j-4:j+1]).diagonal()[::-1] == n))))
    if (temp == []):
        for i in range(7):
            for j in range(7):
                if (arr[i][j] == 0):
                    temp.append((i, j))
        temp_sorted = sorted(temp, key = lambda x : (x[1], -x[0]))
        return (temp_sorted[0])
    temp = list(set(temp))
    temp_sorted = sorted(temp, key = lambda x : (-x[2], x[1], -x[0]))
    return (temp_sorted[0][0:2])

# print (rule4(a, 2))

In [7]:
# check if the game has terminated (either five stones in a row or no available spaces)
def terminate(arr):
    if (np.count_nonzero(arr == 0) == 0):
        return True;
    # horizontal
    for i in range(7):
        for j in range(3):
            if (arr[i][j+1] == 1 and arr[i][j+2] == 1 and arr[i][j+3] == 1 and arr[i][j] == 1 and arr[i][j+4] == 1):
                return True
            if (arr[i][j+1] == 2 and arr[i][j+2] == 2 and arr[i][j+3] == 2 and arr[i][j] == 2 and arr[i][j+4] == 2):
                return True
    # vertical
    for i in range(3):
        for j in range(7):
            if (arr[i+1][j] == 1 and arr[i+2][j] == 1 and arr[i+3][j] == 1 and arr[i][j] == 1 and arr[i+4][j] == 1):
                return True
            if (arr[i+1][j] == 2 and arr[i+2][j] == 2 and arr[i+3][j] == 2 and arr[i][j] == 2 and arr[i+4][j] == 2):
                return True
    # y = -x
    for i in range(3):
        for j in range(3):
            if (arr[i][j] == 1 and arr[i+1][j+1] == 1 and arr[i+2][j+2] == 1 and arr[i+3][j+3] == 1 and arr[i+4][j+4] == 1):
                return True
            if (arr[i][j] == 2 and arr[i+1][j+1] == 2 and arr[i+2][j+2] == 2 and arr[i+3][j+3] == 2 and arr[i+4][j+4] == 2):
                return True
    # y = x
    for i in range(0, 3):
        for j in range(4, 7):
            if (arr[i][j] == 1 and arr[i+1][j-1] == 1 and arr[i+2][j-2] == 1 and arr[i+3][j-3] == 1 and arr[i+4][j-4] == 1):
                return True
            if (arr[i][j] == 2 and arr[i+1][j-1] == 2 and arr[i+2][j-2] == 2 and arr[i+3][j-3] == 2 and arr[i+4][j-4] == 2):
                return True
    return False

# print (terminate(a))

In [8]:
def reflex(arr, n):
    if rule1(arr, n):
        return rule1(arr, n)
    if rule2(arr, n):
        return rule2(arr, n)
    if rule3(arr, n):
        return rule3(arr, n)
    if rule4(arr, n):
        return rule4(arr, n)

In [9]:
def eval(arr, n):
    o = 3 - n
    eval_n = 0
    eval_o = 0
    # check every available five-in-a-row combinations
    # if there are no opponent's stone
    # assign 1 point if 1 agent's stone
    # 10 points if 2 stones/ 100 points if 3 stones/ 1000 points if 4 stones/ 10000 points if 5 stones
    for i in range(7):
        for j in range(3):
            if (np.count_nonzero(arr[i, j:j+5] == o) == 0):
                count = np.count_nonzero(arr[i, j:j+5] == n)
                if (count > 0):
                    eval_n += 10 ** (count - 1)
            if (np.count_nonzero(arr[i, j:j+5] == n) == 0):
                count = np.count_nonzero(arr[i, j:j+5] == o)
                if (count > 0):
                    eval_o += 10 ** (count - 1)
    for i in range(3):
        for j in range(7):
            if (np.count_nonzero(arr[i:i+5, j] == o) == 0):
                count = np.count_nonzero(arr[i:i+5, j] == n)
                if (count > 0):
                    eval_n += 10 ** (count - 1)
            if (np.count_nonzero(arr[i:i+5, j] == n) == 0):
                count = np.count_nonzero(arr[i:i+5, j] == o)
                if (count > 0):
                    eval_o += 10 ** (count - 1)
    for i in range(3):
        for j in range(3):
            if (np.count_nonzero(arr[i:i+5, j:j+5].diagonal() == o) == 0):
                count = np.count_nonzero(arr[i:i+5, j:j+5].diagonal() == n)
                if (count > 0):
                    eval_n += 10 ** (count - 1)
            if (np.count_nonzero(arr[i:i+5, j:j+5].diagonal() == n) == 0):
                count = np.count_nonzero(arr[i:i+5, j:j+5].diagonal() == o)
                if (count > 0):
                    eval_o += 10 ** (count - 1)
    for i in range(0, 3):
        for j in range(4, 7):
            if (np.count_nonzero(np.flipud(arr[i:i+5, j-4:j+1]).diagonal()[::-1] == o) == 0):
                count = np.count_nonzero(np.flipud(arr[i:i+5, j-4:j+1]).diagonal()[::-1] == n)
                if (count > 0):
                    eval_n += 10 ** (count - 1)
            if (np.count_nonzero(np.flipud(arr[i:i+5, j-4:j+1]).diagonal()[::-1] == n) == 0):
                count = np.count_nonzero(np.flipud(arr[i:i+5, j-4:j+1]).diagonal()[::-1] == o)
                if (count > 0):
                    eval_o += 10 ** (count - 1)
    return (eval_n - eval_o)

In [10]:
def minimax(arr, n):
    if (rule1(arr, n)):
        return rule1(arr, n)
    o = 3 - n
    if (rule2(arr, n)):
        return rule2(arr, n)
    spot = [] # list holding all possible positions
    for i in range(7):
        for j in range(7):
            if arr[i][j] == 0:
                spot.append((i,j))
    
    lvl1 = []
    lvl2 = []
    lvl3 = []
    node = 0  # number of nodes expanded
    
    # minimax core
    for x in range(len(spot)):
        spot1 = spot[:x] + spot[x+1:]
        lvl2 = []
        for y in range(len(spot1)):
            spot2 = spot1[:y] + spot1[y+1:]
            lvl3 = []
            for z in range(len(spot2)):
                node = node + 1
                board = np.copy(arr)
                board[spot[x][0],spot[x][1]] = n
                board[spot1[y][0],spot1[y][1]] = o
                board[spot2[z][0],spot2[z][1]] = n
                lvl3.append(eval(board,n))
            lvl2.append(max(lvl3))  # max level 3 (agent's move)
        lvl1.append((min(lvl2), spot[x][0], spot[x][1]))  # min level 2 (opponent's move)
    temp = max(lvl1, key=lambda x : x[0])  # max level 1 (agent's move)
    #print ("minimax: {} nodes".format(node))
    return((temp[1], temp[2])) 

In [12]:
import tkinter as tk
import numpy as np
window = tk.Tk()
window.title('Gomoku')
window.geometry('700x700')
buttonlist = [[0 for col in range(8)] for row in range(8)]
record = np.zeros((7,7))

def checkwin(record):
    countn = 0;
    counto = 0;
    for i in range (0,7):
        for j in range (0,7):
            if(record[i][j]==1):
                countn+=1
                counto=0
                if (countx==5):
                    return 1
            elif(record[i][j]==2):
                counto+=1
                countn=0
                if (counto==5):
                    return 0
        countn=0
        counto=0
    for i in range (0,7):
        for j in range (0,7):
            if(record[j][i]==1):
                countn+=1
                counto=0
                if (countn==5):
                    return 1
            elif(record[j][i]==2):
                counto+=1
                countn=0
                if (counto==5):
                    return 0
        countn=0
        counto=0
    for i in range (0,3):
        for j in range (0,7-i):
            if(record[i+j][j]==1):
                countn+=1
                counto=0
                if (countx==5):
                    return 1
            elif(record[i+j][j]==2):
                counto+=1
                countn=0
                if (counto==5):
                    return 0
        countn=0
        counto=0
    for i in range (0,3):
        for j in range (0,7-i):
            if(record[6-i-j][j]==1):
                countn+=1
                counto=0
                if (countn==5):
                    return 1
            elif(record[6-i-j][j]==2):
                counto+=1
                countn=0
                if (counto==5):
                    return 0
        countn=0
        counto=0
    return -1;
        
        
# on_hit = False  # 默认初始状态为 False
# def hit_me(i,j):
#     global on_hit
#     if on_hit == False:     # 从 False 状态变成 True 状态
#         on_hit = True
#         buttonlist[i][j]['text'] = 'X' 
#         record[i][j] = 1
#         if(checkwin(record)==1):
#             buttonlist[i][j]['text'] = 'X wins'
#         if(checkwin(record)==0):
#             buttonlist[i][j]['text'] = 'O wins'
#     else:       # 从 True 状态变成 False 状态
#         on_hit = False
#         buttonlist[i][j]['text'] = 'O' 
#         record[i][j] = 2
#         if(checkwin(record)==1):
#             buttonlist[i][j]['text'] = 'X wins'
#         if(checkwin(record)==0):
#             buttonlist[i][j]['text'] = 'O wins'

def hit_me(i,j):
    buttonlist[i][j]['text'] = 'O'   # 设置标签的文字为 'you hit me'
    record[i][j] = 1
    pos = minimax(record, 2)
    buttonlist[pos[0]][pos[1]]['text'] = 'X'
    record[pos[0]][pos[1]] = 2
    

for i in range(0,7):
    for j in range(0,7):
        btn = buttonlist[i][j]
        buttonlist[i][j] = tk.Button(window, text=" ", width=10, height=4, command = lambda x = i, y = j: hit_me(x, y), bg = 'white', bd=2)
        buttonlist[i][j].grid(row=i, column=j, sticky='W'+'N')

window.mainloop()

minimax: 103776 nodes
minimax: 91080 nodes
minimax: 79464 nodes
minimax: 68880 nodes
minimax: 59280 nodes
minimax: 50616 nodes
minimax: 35904 nodes
